### ISSUE TITLE
Location's isValid looks wrong.

### ISSUE THREAD

**Issue by earthiverse** [cmput402w2016/CMPUT402W16T1#10]
Here's a simplified version from the function I saw in 3a048879765e002b393acb6ad703b6b71cd927cf:

```
public boolean isValid() {
  return this.lat != null
    && this.lon != null
    && -90.0 < this.lat
    && this.lat < 90.0
    && this.lon < -180.0
    && this.lon > 180.0;
}
```

Checks on longitude look backwards. Also, weird syntax on flipping the negative latitude check...

**Comment by awwong1** [comment]
Right, I'll fix that

**Comment by awwong1** [comment]
https://github.com/cmput402w2016/CMPUT402W16T1/commit/87ceb05e3cd3a26572b71ac275eea4c7cecc5ce1
