### ISSUE TITLE
Server goes down constantly

### ISSUE THREAD

**Issue by earthiverse** [cmput402w2016/CMPUT402W16T1#11]
Not really related to git, but up here to let other teams know what's going on.

Essentially, there's something wrong with Cybera that makes writes to disk take a really really long time... Apparently the issue also happens on some cheaper AWS instances, but I saw Amazon gave a statement after it happened that it was not supposed to happen...

We can't fix it currently on our side, the current fix is to simply restart the instance when it stops responding. We have to start it from the Cybera manger, you can't SSH in.

> [60960.320137] INFO: task jbd2/vda1-8:248 blocked for more than 120 seconds.
> [60960.331158]       Not tainted 3.19.0-51-generic #58~14.04.1-Ubuntu
> [60960.333237] "echo 0 > /proc/sys/kernel/hung_task_timeout_secs" disables this message.
> [60960.337170] INFO: task postgres:1148 blocked for more than 120 seconds.
> [60960.340507]       Not tainted 3.19.0-51-generic #58~14.04.1-Ubuntu
> [60960.343485] "echo 0 > /proc/sys/kernel/hung_task_timeout_secs" disables this message.
> [60960.347120] INFO: task postgres:1149 blocked for more than 120 seconds.
> [60960.350001]       Not tainted 3.19.0-51-generic #58~14.04.1-Ubuntu
> [60960.352727] "echo 0 > /proc/sys/kernel/hung_task_timeout_secs" disables this message.
> [60960.355709] INFO: task python:1355 blocked for more than 120 seconds.
> [60960.357798]       Not tainted 3.19.0-51-generic #58~14.04.1-Ubuntu
> [60960.359791] "echo 0 > /proc/sys/kernel/hung_task_timeout_secs" disables this message.
> [60960.363411] INFO: task python:1356 blocked for more than 120 seconds.
> [60960.366645]       Not tainted 3.19.0-51-generic #58~14.04.1-Ubuntu
> [60960.368630] "echo 0 > /proc/sys/kernel/hung_task_timeout_secs" disables this message.
> [60960.371297] INFO: task postgres:1312 blocked for more than 120 seconds.
> [60960.373439]       Not tainted 3.19.0-51-generic #58~14.04.1-Ubuntu
> [60960.375439] "echo 0 > /proc/sys/kernel/hung_task_timeout_secs" disables this message.
> [60960.378193] INFO: task postgres:1313 blocked for more than 120 seconds.
> [60960.380373]       Not tainted 3.19.0-51-generic #58~14.04.1-Ubuntu
> [60960.382666] "echo 0 > /proc/sys/kernel/hung_task_timeout_secs" disables this message.
> [60960.385386] INFO: task java:9552 blocked for more than 120 seconds.
> [60960.387397]       Not tainted 3.19.0-51-generic #58~14.04.1-Ubuntu
> [60960.389387] "echo 0 > /proc/sys/kernel/hung_task_timeout_secs" disables this message.
> [60960.392056] INFO: task java:7828 blocked for more than 120 seconds.
> [60960.394053]       Not tainted 3.19.0-51-generic #58~14.04.1-Ubuntu
> [60960.396083] "echo 0 > /proc/sys/kernel/hung_task_timeout_secs" disables this message.
> [60960.398766] INFO: task java:9778 blocked for more than 120 seconds.
> [60960.401315]       Not tainted 3.19.0-51-generic #58~14.04.1-Ubuntu
> [60960.403360] "echo 0 > /proc/sys/kernel/hung_task_timeout_secs" disables this message.

**Comment by awwong1** [comment]
Seems to be solved by allocating more disk space in Cybera, setting swap partition. Gj Kent
