### ISSUE TITLE
Fix HBase Model for Traffic

### ISSUE THREAD

**Issue by earthiverse** [cmput402w2016/CMPUT402W16T1#15]
Diego's worry is that "in the traffic table, as Hbase partitions the tables based on rowkey and column family ... [since]  there is only one column family, and each rowkey will have associated millions of cells, eventually."

It's true. If you added one piece of "data" every minute, for each unique "data", we would have ~520,000 columns added per year.

Hence, I propose adding at least the year to the row key.

Right now the row key is `geohashFROM_geohashTO`. I propose `geohashFROM_geohashTO_YYYY` where `YYYY` is the year of the data.

**Comment by awwong1** [comment]
Done as of 9316603ecc3b4729be98beb6bd1f71cbc7f49ca1
