### ISSUE TITLE
User Interface Feedback

### ISSUE THREAD

**Issue by awwong1** [cmput402w2016/CMPUT402W16T1#4]
- Explicitly use traffic like keys for storing values in the tags, no example was given and marks were taken off due to some miscommunication
  - Add in specific, explicitly and pedantically defined JSON objects per sample API route
- Add in an example where multiple JSON objects can be processed at once, versus one at a time

**Comment by earthiverse** [comment]
Additional examples are provided. Further functionality will probably be defined, I think there's a better way to say what we're going to do in the wiki, but for now this should suffice.
I'm going to leave the issue open until I feel satisfied.

**Comment by awwong1** [comment]
Closed, Project Part 2 deadline has passed. Feedback was provided.
